server:
  port: 8080
  host: localhost
mysql:
  host: localhost
  port: 3306
  user: root
  password: 123456
  database: testgo
  maxIdleConns: 10 # max idle connections
  maxOpenConns: 100 # max open connections
  connMaxLifetime: 3600 # connection max lifetime
redis:
  host: localhost
  port: 6379
logger:
  file_name: "./storage/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
  log_level: debug
